### ISSUE TITLE
Add implementation of TaskDetails

### ISSUE THREAD

**Issue by m-shulipa** [dv00d00/BinaryStudio.TaskManager#11]
It should be like ManagerDetailsView.

**Comment by m-shulipa** [comment]
In the future, maybe, we will add feature of edit without button "Edit" - just for Input (Text)? Or leave as is?

**Comment by dv00d00** [comment]
We may have two ways of editting task. 
Quick edit will allow user to edit description of the task or leave a comment. This is not related to this task.
Task details should be implemented just like manager details
