### ISSUE TITLE
Changind in TaskPriority

### ISSUE THREAD

**Issue by m-shulipa** [dv00d00/BinaryStudio.TaskManager#123]
From dropdown lins to one small button group like this
http://twitter.github.com/bootstrap/components.html#buttonGroups

or like this
http://twitter.github.com/bootstrap/javascript.html#buttons

**Comment by m-shulipa** [comment]
Work on this functional in EditTask

**Comment by msemenistyi** [comment]
it would be great buttons to have different colors

**Comment by m-shulipa** [comment]
@nikeiwe it wiil be great, but we must store color near the value - now it works independent of priority number!
