### ISSUE TITLE
Fix UnitTest 

### ISSUE THREAD

**Issue by m-shulipa** [dv00d00/BinaryStudio.TaskManager#9]
ShouldNot_AssignTask_WhenSuchEmployeeDoesNotExist
and
Should_UpdateTaskAndDeleteRelatedReminders_WhenMoveTaskIsCalled
need to be fixed.
Before working on issue make sure that part of program with ReminderRepository is implements

**Comment by msemenistyi** [comment]
Tests were fine, but implementation of TaskPrcoseccor itself was finished, so now they are successful
